### ISSUE TITLE
"TELEGRAM_TOKEN is required" error / can't get bot running

### ISSUE THREAD

**Issue by Stimmenhotel** [kimmobrunfeldt/ppmusicbot#11]
Hey kimmobrunfeldt,
I saw your bot mentioned on reddit and I love the idea about collecting all links into a playlist.
Sadly I don't have any knowledge in nodejs and have no time yet to dive into it (i am writing my bachelor thesis right now).
The whole repo is a few years old, but I hope you still support it.

About the error:
I have collected a few informations about the error in the reddit post [here.](https://www.reddit.com/r/TelegramBots/comments/f3d2fu/telegram_spotify_bot/)

Basicly I can't tun the bot, even I have added (nearly) all env variables, but npm seems not to recognize the Bot token.

I am not the only one having this problems, though.

Could you have a look?

**Comment by PaulSonOfLars** [comment]
You've not provided much information to debug this, other than "this doesn't work". Could you give more information, such as what "added nearly all env variables" means? Which ones did you not add? 
And from the title, are you sure you've added an env variable for  "TELEGRAM_TOKEN"?

**Comment by Stimmenhotel** [comment]
Sure, sorry for not posting things here, much informations are over at reddit (see the link in my post)
I haven't added variables for SPOTIFY_REFRESH_TOKEN and  REDIS_URL. 
The telegram token was the easiest to obtain and worked with a easy sample bot right away. (one that only says hello if triggered) 

If needed I will copy all informations from the reddit post into this issue, but it's short after midnight overhere, I will do that tomorrow :)

**Comment by PaulSonOfLars** [comment]
What is the output of
`env | grep TELEGRAM`?

**Comment by Stimmenhotel** [comment]
Output after "npm install"
```

 npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
 npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
 npm WARN deprecated superagent@2.3.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
 npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
 npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
 npm notice created a lockfile as package-lock.json. You should commit this file.
 added 436 packages from 588 contributors and audited 1362 packages in 23.285s
 
 5 packages are looking for funding
   run `npm fund` for details
 
 found 34 vulnerabilities (18 low, 4 moderate, 11 high, 1 critical)
   run `npm audit fix` to fix them, or `npm audit` for details



```
Output aftert npm start
```

> ppmusicbot@1.0.0 start /home/rudiger/Schreibtisch/ppmusicbot-master
> bin/hubot -a telegram


[Sat Mar 14 2020 14:12:14 GMT+0100 (GMT+01:00)] INFO Telegram Adapter Bot undefined Loaded...
Error: The environment variable "TELEGRAM_TOKEN" is required.
  at Telegram.run (/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/hubot-telegram/src/telegram.coffee:217:7, <js>:247:28)
  at Robot.run (/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (internal/modules/cjs/loader.js:778:30)
  at Object.exports.run (/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ppmusicbot@1.0.0 start: `bin/hubot -a telegram`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ppmusicbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rudiger/.npm/_logs/2020-03-14T13_12_14_763Z-debug.log


```

content of the debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ppmusicbot@1.0.0~prestart: ppmusicbot@1.0.0
6 info lifecycle ppmusicbot@1.0.0~start: ppmusicbot@1.0.0
7 verbose lifecycle ppmusicbot@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ppmusicbot@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/rudiger/Schreibtisch/ppmusicbot-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle ppmusicbot@1.0.0~start: CWD: /home/rudiger/Schreibtisch/ppmusicbot-master
10 silly lifecycle ppmusicbot@1.0.0~start: Args: [ '-c', 'bin/hubot -a telegram' ]
11 silly lifecycle ppmusicbot@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle ppmusicbot@1.0.0~start: Failed to exec start script
13 verbose stack Error: ppmusicbot@1.0.0 start: `bin/hubot -a telegram`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid ppmusicbot@1.0.0
15 verbose cwd /home/rudiger/Schreibtisch/ppmusicbot-master
16 verbose Linux 4.15.0-88-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error ppmusicbot@1.0.0 start: `bin/hubot -a telegram`
22 error Exit status 1
23 error Failed at the ppmusicbot@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


```
-----------------------------------------------------


Output of `env | grep TELEGRAM` is nothing.
The .env file with my token is lying in the root dictionary of the ppmusicbot.
